"""Augment Baby1 story-observations with review-approved story chapters.

Loads data/story-observations.js (generated by build-story-observations.py),
appends new visually-reviewed chapters, and rewrites the file. Idempotent:
chapters whose sceneId already exists are skipped. Media already claimed by
existing events/milestones is filtered out of new chapters. Non-sensitive
chapter images are added to previewCandidates so cards show previews; the
Vung-Tau-style sensitive chapters contribute only excludePreview.

After the original compiler (build-story-observations.py) is re-run, this
script must be re-run too.
"""
import json
import re
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
ROOT = BASE.parent
OBS = BASE / "data" / "story-observations.js"
IMG = "./assets/thuy-yen/images"
VID = "./assets/thuy-yen/videos"


def media(*names):
    out = []
    for n in names:
        folder = "videos" if n.endswith(".mp4") else "images"
        out.append(f"./assets/thuy-yen/{folder}/{n[:4]}/{n[5:7]}/{n}")
    return out


CHAPTERS = [
 {"sceneId": "yen-ch01-nu-cuoi-dau-tien", "date": "2021-05-03", "importance": 5,
  "title": "Nụ cười đầu tiên",
  "story": "Đầu tháng 05/2021, Yên được một tháng tuổi. Mẹ áp má vào má con, và lần đầu tiên Yên đáp lại bằng một nụ cười giòn tan trên bộ đồ in hình cà rốt — cả nhà lần lượt bấm máy. Cũng trong những ngày này, con có buổi tắm chậu xanh đầu đời, chân đạp nước tí tách. Một tháng rưỡi — và con đã biết cách khiến cả nhà phải ngừng lại chỉ để nhìn mình cười.",
  "media": media("2021-05-03_10.webp","2021-05-03_12.webp","2021-05-03_16.webp","2021-05-03_19.webp","2021-05-03_20.webp","2021-05-04_3.webp","2021-05-04_4.webp","2021-05-04_6.webp","2021-05-04_8.webp"),
  "evidence": ["Contact sheets 001-002: má áp má 03/05, cười giòn 04/05, tắm chậu đầu 03/05/2021"],
  "context": "Ảnh tại nhà, Yên ~1 tháng tuổi."},
 {"sceneId": "yen-ch02-hoa-son", "date": "2022-01-29", "importance": 4,
  "title": "Bộ ảnh hoa son",
  "story": "29/01/2022, Yên chín tháng tuổi, mặc yếm trắng được chụp giữa khóm hoa son rực đỏ. Con ngồi giữa hoa, chộp lấy cánh hoa, nhìn ngơ ngác rồi cười. Gần ba mươi khung hình được bấm trong một buổi — bộ ảnh đẹp nhất của Yên thời chưa tròn một tuổi.",
  "media": media("2022-01-29_4.webp","2022-01-29_8.webp","2022-01-29_10.webp","2022-01-29_16.webp","2022-01-29_25.webp"),
  "evidence": ["Contact sheet 006: chụp giữa hoa son ~30 khung 29/01/2022"],
  "context": "Buổi chụp ảnh giữa khóm hoa, Yên 9 tháng tuổi."},
 {"sceneId": "yen-ch03-tet-dau-tien", "date": "2022-02-12", "importance": 5,
  "title": "Tết đầu tiên và chiếc SUV vàng",
  "story": "Tết Nhâm Dần 2022 là Tết đầu tiên Yên “tham gia” bằng mắt: con mặc đồ cam rực, được chụp trên nền quạt vàng hồng lộng lẫy. Rồi خارج sân, con tự tay cầm lái chiếc SUV điện vàng, mặt đắc ý như tay đua chuyên nghiệp. Mười tháng tuổi — Yên đã có bằng lái trong imagination của cả nhà.",
  "media": media("2022-02-12_14.webp","2022-02-12_18.webp","2022-02-12_21.webp","2022-02-12_2.webp","2022-02-12_5.webp","2022-02-12_7.webp","2022-02-19.webp"),
  "evidence": ["Contact sheets 008-009: Tết đồ cam + lái SUV điện vàng 12/02/2022, 19/02 đi xe máy cùng bố"],
  "context": "Tết Nguyên đán 2022, Yên 10 tháng tuổi; ảnh cuối là buổi đi xe máy cùng bố."},
 {"sceneId": "yen-ch04-san-thuong-canh-lan", "date": "2022-03-01", "importance": 3,
  "title": "Sân thượng và cành lan tím vàng",
  "story": "01/03/2022, trưa nắng ấm, Yên mặc đồ vàng ngồi trên sân thượng cạnh chậu lan tím vàng. Con chộp lấy cành lan, tò mò xem lá cây là thứ gì, cười khúc khích giữa rèm trắng. Mười một tháng — và đây là những tấm ảnh “gần đi” cuối cùng: tháng sau, con sẽ biết đi thật.",
  "media": media("2022-03-01_10.webp","2022-03-01_13.webp","2022-03-01_16.webp","2022-03-01_21.webp","2022-03-01_24.webp"),
  "evidence": ["Contact sheets 010-011: sân thượng chậu lan 01/03/2022 ~15 khung"],
  "context": "Trưa 01/03/2022 trên sân thượng nhà."},
 {"sceneId": "yen-ch05-ky-niem-mot-tuoi", "date": "2022-04-06", "importance": 5,
  "title": "Kỷ niệm một tuổi giữa rừng hoa",
  "story": "Hai ngày sau sinh nhật tròn một tuổi (04/04), Yên có riêng một buổi chụp kỷ niệm: váy len vàng, ngồi giữa thảm cỏ giả và rừng hoa — lung linh như một nàng thơ. Vài ngày trước đó, con còn được tặng chiếc ô tô điện đỏ còn bọc màng, và “làm việc cùng bố” bằng cách bò lên bàn phím laptop. Mười hai tháng: biết đi, biết tự ăn, và biết chiếm trọn bàn làm việc của ba.",
  "media": media("2022-04-02_10.webp","2022-04-02_11.webp","2022-04-06_2.webp","2022-04-06_6.webp","2022-04-06_9.webp","2022-04-08.webp"),
  "evidence": ["Contact sheet 017-018: bộ ảnh váy vàng 06/04/2022, ô tô điện 02/04, bàn phím 08-09/04"],
  "context": "Các buổi chụp và sinh hoạt đầu tháng 04/2022, quanh ngày sinh nhật tròn 1 tuổi."},
 {"sceneId": "yen-ch06-cuu-hoa-chay", "date": "2022-05-16", "importance": 4,
  "title": "Chiến sĩ chữa cháy tập sự",
  "story": "16/05/2022, ở trung tâm thương mại, Yên thử tai nghe lông mũ xong “trúng tuyển” vị trí cứu hỏa tập sự: con đứng cạnh bình chữa cháy đỏ to hơn mình, ôm chặt không buông, nhìn nó như một người bạn mới. Cả trung tâm đi hết một vòng — từ giỏ hàng siêu thị tới khu đồ chơi — và bình chữa cháy vẫn là “món” Yên thích nhất ngày hôm đó.",
  "media": media("2022-05-16_11.webp","2022-05-16_13.webp","2022-05-16_16.webp","2022-05-16_20.webp","2022-05-16_26.webp","2022-05-16_31.webp"),
  "evidence": ["Contact sheets 020-021: tai nghe lông + bình chữa cháy 16/05/2022"],
  "context": "Đi TTTM 16/05/2022, Yên ~13 tháng."},
 {"sceneId": "yen-ch07-xe-mo-to-cua-ba", "date": "2022-05-22", "importance": 4,
  "title": "Xe mô tô của ba",
  "story": "22/05/2022, Yên váy hồng được đặt lên yên chiếc mô tô phân khối lớn cam-đen của ba. Con nắm tay lái như người có kinh nghiệm, mặt nghiêm túc “kiểm tra xe” trước giờ xuất phát. Từ ngày ấy, mỗi lần ba dọn xe là Yên lại đòi “xí chỗ” — hành khách nhỏ tuổi nhưng tự tin nhất.",
  "media": media("2022-05-22_3.webp","2022-05-22_5.webp","2022-05-22_9.webp","2022-05-22_13.webp"),
  "evidence": ["Contact sheet 022: Yên trên mô tô phân khối 22/05/2022"],
  "context": "Chụp tại sân nhà, xe mô tô của ba."},
 {"sceneId": "yen-ch08-xe-dap-hong", "date": "2022-05-25", "importance": 4,
  "title": "Chiếc xe đạp ba bánh hồng đầu tiên",
  "story": "25/05/2022, cả nhà dẫn Yên đi tiệm xe đạp trẻ em. Giữa hàng loạt xe, con chọn ngay chiếc ba bánh hồng, leo lên ngồi thử và không chịu xuống. Ba ngày sau mốc “biết đi” đầu tiên, Yên chính thức có phương tiện riêng — và hành trình “tự mình di chuyển” bắt đầu từ đây.",
  "media": media("2022-05-25_11.webp","2022-05-25_16.webp","2022-05-25_20.webp","2022-05-25_23.webp"),
  "evidence": ["Contact sheet 023: thử xe đạp ba bánh hồng 25/05/2022"],
  "context": "Tiệm xe đạp trẻ em, Yên vừa tròn 13 tháng."},
 {"sceneId": "yen-ch09-bong-bay-trang", "date": "2022-06-04", "importance": 4,
  "title": "Quả bóng bay trắng",
  "story": "04/06/2022, Yên có quả bóng bay trắng đầu tiên. Con ôm bóng đi khắp trung tâm thương mại như ôm một món quà lớn, rồi buổi chiều được chụp trước phông biển với ghế tắm nắng. Bóng bay — thứ đồ chơi rẻ nhất nhưng với con thì bằng cả một buổi lễ.",
  "media": media("2022-06-04_13.webp","2022-06-04_17.webp","2022-06-04_22.webp","2022-06-04_28.webp","2022-06-04_33.webp"),
  "evidence": ["Contact sheets 024-025: bóng bay trắng + phông biển 04/06/2022"],
  "context": "Đi chơi 04/06/2022, Yên 14 tháng."},
 {"sceneId": "yen-ch10-vac-can-nuoc", "date": "2022-06-18", "importance": 3,
  "title": "Bé vác can nước khổng lồ",
  "story": "Chiều 16/06/2022, đội mũ lưỡi trai, Yên “vác” chiếc can nước xanh to gấp đôi người, bước đi như một người đưa nước chuyên nghiệp. Người xem cười nghiêng ngả, còn con thì rất tự hào về nhiệm vụ của mình. Tuổi con, mọi việc đều nghiêm túc — kể cả vác nước.",
  "media": media("2022-06-18_1.webp","2022-06-18_3.webp","2022-06-18_6.webp","2022-06-12_2.webp","2022-06-12_3.webp"),
  "evidence": ["Contact sheet 027: vác can nước 16-18/06/2022; mũ hồng 12/06/2022"],
  "context": "Chiều 16/06/2022 tại nhà; ảnh cuối là buổi đội mũ hồng đi chơi 12/06."},
 {"sceneId": "yen-ch11-khan-sung-huoc", "date": "2022-07-09", "importance": 4,
  "title": "Khăn sừng hươu và nụ cười tít mắt",
  "story": "08-09/07/2022, cả nhà cùng đội cho Yên chiếc khăn mũ có sừng hươu. Con cười tít mắt trong chiếc khăn ngộ nghĩnh, chụp say sưa cả tối. Mười lăm tháng tuổi — giai đoạn mà mỗi lần cười là cả nhà cười theo.",
  "media": media("2022-07-09_2.webp","2022-07-09_5.webp","2022-07-09_6.webp","2022-07-09_3_1.webp"),
  "evidence": ["Contact sheet 028: khăn sừng hươu 08-09/07/2022"],
  "context": "Tối 08-09/07/2022 tại nhà."},
 {"sceneId": "yen-ch12-cam-dua-dau-tien", "date": "2022-08-04", "importance": 4,
  "title": "Bé cầm đũa lần đầu",
  "story": "04/08/2022, bữa cơm có yếm “Che” cho Yên và một sự kiện lớn: con cầm đũa lần đầu. Cả bàn người lớn ngừng ăn để xem Yên chăm chú gắp — chưa gắp nổi miếng nào, nhưng tư thế thì chuẩn không cần chỉnh. Ăn văng cơm ra mâm là chuyện đương nhiên; sự kiên trì mới là thứ đáng nhớ.",
  "media": media("2022-08-04_2.webp","2022-08-04_3.webp","2022-08-04_10.webp","2022-08-04_16.webp"),
  "evidence": ["Contact sheets 029-030: tiệc cầm đũa 04/08/2022"],
  "context": "Bữa cơm gia đình 04/08/2022, Yên 16 tháng."},
 {"sceneId": "yen-ch13-ve-que-xem-ca", "date": "2022-08-26", "importance": 3,
  "title": "Về quê xem chậu cá",
  "story": "Cuối tháng 08/2022, Yên theo cả nhà về quê. Trước khi đi, con có một buổi đi siêu thị rất chuyên nghiệp — tự bước giữa các quầy, nhìn ngắm tất cả. Ở quê, thứ khiến con không rời mắt là chậu cá đỏ: xô xệch đầu nhìn cá bơi, gọi ơm ơm. Chuyến về quê đầu tiên trong đợt hè ấy — và cá là kỷ niệm lớn nhất.",
  "media": media("2022-08-25_10.webp","2022-08-25_12.webp","2022-08-26.webp","2022-08-26_1.webp","2022-08-26_2.webp","2022-08-26_3.webp"),
  "evidence": ["Contact sheets 034-035: siêu thị 25/08 + về quê chậu cá 26/08/2022"],
  "context": "25-26/08/2022; siêu thị trước chuyến về quê."},
 {"sceneId": "yen-ch14-net-ve-dau-tien", "date": "2022-09-06", "importance": 4,
  "title": "Nét vẽ đầu tiên",
  "story": "06/09/2022, mẹ nắm tay Yên cầm bút dạ vẽ những nét nguệch ngoạc đầu tiên. Sau đó con tự ngồi với hộp màu, nghiêm túc như một họa sĩ nhỏ. Mười bảy tháng tuổi — con bắt đầu “sáng tác”. Mười ngày sau, hai bố con đeo khăn hồng chụp loạt ảnh hài hước, để khép lại một mùa thu đầy màu sắc.",
  "media": media("2022-09-06.webp","2022-09-06_1.webp","2022-09-06_3.webp","2022-09-06_4.webp","2022-09-16_1.webp","2022-09-16_4.webp","2022-09-16_6.webp"),
  "evidence": ["Contact sheets 036-037: vẽ đầu tiên 06/09 + bố con khăn hồng 16/09/2022"],
  "context": "Ảnh tại nhà; 6 ảnh cuối là buổi chụp bố con đội khăn hồng 16/09/2022."},
 {"sceneId": "yen-ch15-selfie-cha-con", "date": "2022-11-22", "importance": 4,
  "title": "Buổi selfie của hai bố con",
  "story": "22/11/2022 là ngày của hai bố con: ba mặc áo polo đỏ, Yên ngậm ti giả, hai bố con áp má vào nhau chụp liền mười lăm tấm selfie. Rồi đến lượt Yên tự cầm máy — ba tấm tự chụp mặt ngây ngô vô cùng đáng yêu. Mười chín tháng tuổi, và Yên đã biết “lấy correct góc”.",
  "media": media("2022-11-22.webp","2022-11-22_2.webp","2022-11-22_6.webp","2022-11-22_9.webp","2022-11-22_14.webp","2022-11-22_15.webp"),
  "evidence": ["Contact sheet 045: selfie bố con + Yên tự chụp 22/11/2022"],
  "context": "Tối 22/11/2022 tại nhà."},
 {"sceneId": "yen-ch16-xe-may-dien-mickey", "date": "2023-02-18", "importance": 4,
  "title": "Xe máy điện và chiếc mũ Mickey",
  "story": "18/02/2023, Yên đội mũ Mickey, áo vàng quần đỏ, ngồi lên chiếc xe máy điện nhí trước cửa hàng — mặt kiêu hãnh như tay đua vô địch. Tuần trước đó, con còn là “fashion icon” với kính râm to và áo LOVE YOU, pose mặt nghiêm túc chụp cả loạt. Hai tuổi — và Yên đã có phong cách riêng.",
  "media": media("2023-02-10_13.webp","2023-02-10_14.webp","2023-02-18.webp","2023-02-18_1.webp","2023-02-18_3.webp"),
  "evidence": ["Contact sheets 052-053: kính râm 10/02 + mũ Mickey xe máy điện 18/02/2023"],
  "context": "Ảnh tháng 02/2023, Yên ~22 tháng."},
 {"sceneId": "yen-ch17-vuong-mi-hai-tuoi", "date": "2023-03-15", "importance": 5,
  "title": "Tiệc sinh nhật hai tuổi với vương miện",
  "story": "15/03/2023, Yên được tổ chức sinh nhật hai tuổi sớm tại nhà hàng tiệc cưới rộng rãi: con mặc áo đỏ, đội vương miện nhỏ, ngồi cạnh mẹ trước chiếc bánh kem lớn. Con thổi nến, gõ đàn đồ chơi, được mọi người vỗ tay. Bánh kem, vương miện và một em bé trong bụng mẹ sắp chào đời — tháng 03/2023, gia đình mình đang đếm ngược ngày gặp Cá.",
  "media": media("2023-03-15_13.webp","2023-03-15_18.webp","2023-03-15_30.webp","2023-03-15_40.webp"),
  "evidence": ["Contact sheet 054: tiệc sinh nhật nhà hàng tiệc cưới, Yên đội vương miện 15/03/2023"],
  "context": "Tiệc sinh nhật 2 tuổi (tổ chức sớm) của Yên tại nhà hàng."},
 {"sceneId": "yen-ch18-nang-tho-kinh-lech", "date": "2023-04-23", "importance": 3,
  "title": "Nàng thơ kính lệch và chú hươu vàng",
  "story": "23/04/2023, Yên đeo chiếc kính râm lệch một bên, áo cam, ngồi trên sofa sofa pose như một nàng thơ đúng chuẩn. Hai tuần sau, con cưỡi chú hươu gỗ vàng, tóc bay trong gió, kèm buổi đứng hiên nhà cầm ô chờ mưa. Hai tuổi rưỡi — giai đoạn mà mọi thứ con làm đều thành ảnh đẹp.",
  "media": media("2023-04-23_6.webp","2023-04-23_8.webp","2023-04-23_10.webp","2023-05-05_5.webp","2023-05-07.webp","2023-05-07_1.webp"),
  "evidence": ["Contact sheets 056-057: kính lệch 23/04, ô mưa 05/05, hươu vàng 07/05/2023"],
  "context": "Các buổi chụp cuối 04 - đầu 05/2023."},
 {"sceneId": "yen-ch19-rang-sua", "date": "2023-08-23", "importance": 4,
  "title": "Răng sữa và nụ cười mở to",
  "story": "23/08/2023, ống kính chụp cận bắt trọn nụ cười mở to của Yên — hàng răng sữa đều tăm tắp lần đầu hiện rõ trong ảnh. Tuần sau, con còn có cả series “mặt lì lợm” cận cảnh. Hai tuổi chín tháng: giai đoạn mà mỗi nụ cười đều đủ làm cả nhà quên hết mệt mỏi.",
  "media": media("2023-08-23.webp","2023-08-23_2.webp","2023-09-14_2.webp","2023-09-14_4.webp"),
  "evidence": ["Contact sheets 060-061: cười cận răng sữa 23/08 + mặt lì 14/09/2023"],
  "context": "Ảnh cận tại nhà, tháng 08-09/2023."},
 {"sceneId": "yen-ch20-tran-bam-lan-dau", "date": "2023-10-23", "importance": 4, "sensitive": True,
  "title": "Trán bầm — lần chấn thương đầu",
  "story": "23-24/10/2023, Yên bị té đập trán — vết bầm hiện rõ và gia đình theo dõi con nhiều ngày liền. Là lần chấn thương đầu tiên của con, và cũng là lần cả nhà học được cách bình tĩnh chăm sóc vết thương. Con hồi phục nhanh, và nụ cười trở lại sớm hơn cả sự lo lắng.",
  "media": media("2023-10-23.webp","2023-10-24_2.webp","2023-10-24_8.webp"),
  "evidence": ["Contact sheet 061: chấn thương trán theo dõi 23-24/10/2023"],
  "context": "Ảnh theo dõi vết bầm trán sau cú té; gia đình chăm sóc tại nhà."
 },
 {"sceneId": "yen-ch21-ong-noi-va-yen", "date": "2023-11-26", "importance": 4,
  "title": "Ông nội và Yên",
  "story": "26/11/2023, ông nội ngồi trên chiếc ghế nhựa quen thuộc bế Yên váy hồng trên tay. Cháu gạ gẫm, ông dỗ dành, hai ông cháu cười với nhau suốt một loạt mười tấm ảnh. Tình ông cháu không cần dịp đặc biệt — chỉ cần một chiếc ghế nhựa và một buổi chiều rảnh.",
  "media": media("2023-11-26_4_52.webp","2023-11-26_8_52.webp","2023-11-26_10_52.webp"),
  "evidence": ["Contact sheet 062: ông nội bế Yên 26/11/2023"],
  "context": "Chiều 26/11/2023 tại nhà."},
 {"sceneId": "yen-ch22-noel-som", "date": "2023-12-15", "importance": 4,
  "title": "Giáng sinh sớm giữa trung tâm thương mại",
  "story": "15/12/2023, giữa TTTM đã lên cây thông trắng và tuyết trang trí, Yên mặc váy cam ôm quả bóng đứng chụp — rực rỡ như một tờ thiệp Noel sống. Hai năm trước, con còn quá nhỏ để biết Noel là gì; năm nay con đã biết chỉ tay vào ông tuyết và đòi chụp hình.",
  "media": media("2023-12-15.webp","2023-12-15_2.webp","2023-12-15_4.webp"),
  "evidence": ["Contact sheet 062: Noel TTTM 15/12/2023"],
  "context": "Đi TTTM mùa Noel 15/12/2023."},
 {"sceneId": "yen-ch23-sung-nuoc", "date": "2023-12-18", "importance": 4,
  "title": "Súng nước tưới cả khu vườn",
  "story": "18/12/2023, Yên đeo túi gấu trúc, mang “vũ khí” súng nước hồng ra sân và phun tưới… toàn bộ khu vườn. Phun lá, phun chậu, phun cả vòi nước, cười nghiêng ngả suốt hai mươi lăm tấm ảnh. Mùa đông mà chơi nước — nhưng với Yên, vui thì không phân biệt mùa.",
  "media": media("2023-12-18.webp","2023-12-18_6.webp","2023-12-18_9.webp","2023-12-18_20.webp","2023-12-18_22.webp"),
  "evidence": ["Contact sheet 063: súng nước 18/12/2023 ~25 khung"],
  "context": "Chiều 18/12/2023 tại sân nhà."},
 {"sceneId": "yen-ch24-khach-hang-ti-hon", "date": "2024-01-05", "importance": 3,
  "title": "Khách hàng tí hon",
  "story": "05/01/2024, ở siêu thị, Yên váy jeans đeo kính hồng tự tay kéo chiếc xe đẩy nhí đi giữa kệ đồ chơi, một tay còn văng vẳng quả bóng rổ. Người lớn đi theo chỉ để đảm bảo an toàn — còn con thì tự tin mua sắm như một khách hàng kỳ cựu.",
  "media": media("2024-01-05.webp","2024-01-05_1_1.webp","2024-01-05_5.webp"),
  "evidence": ["Contact sheet 063: kéo xe đẩy siêu thị 05/01/2024"],
  "context": "Đi siêu thị đầu năm 2024, Yên 2 tuổi 9 tháng."},
 {"sceneId": "yen-ch25-ngai-vang-va-elsa", "date": "2024-05-12", "importance": 4,
  "title": "Ngai vàng và váy Elsa",
  "story": "12/05/2024, Yên được chụp trên “ngai vàng” ươm vàng nhân dịp sinh nhật muộn — trang trọng như một nữ hoàng nhỏ. Đến ngày 01/06 Tết thiếu nhi, con khoác váy xanh Elsa đến khu vui chơi, khoe váy tự tin không kém công chúa phim hoạt hình. Tháng của trẻ con — và Yên có hai dịp, hai bộ váy, gấp đôi vui.",
  "media": media("2024-05-12.webp","2024-05-12_2.webp","2024-05-12_3.webp","2024-05-12_8.webp","2024-06-01_10.webp","2024-06-01_16.webp"),
  "evidence": ["Contact sheets 065-066: ngai vàng 12/05 + váy Elsa ngày 01/06/2024"],
  "context": "Sinh nhật muộn 12/05 và Tết thiếu nhi 01/06/2024."},
 {"sceneId": "yen-ch26-sinh-nhat-nam-tuoi", "date": "2026-04-10", "importance": 5,
  "title": "Sinh nhật năm tuổi dưới ánh vàng",
  "story": "10/04/2026, Yên đón sinh nhật lần thứ năm trong ánh đèn vàng ấm: bánh kem đặt giữa bàn, cả nhà quây quần, hai chị em cùng lên hình. Ba tuần trước, con còn có bộ ảnh “váy hồng trước thác nước” nhân dịp dã ngoại. Năm tuổi — Yên lớn nhanh đến mức mỗi lần nhìn lại ảnh cũ, cả nhà đều giật mình.",
  "media": media("2026-02-22_10.webp","2026-02-22_12.webp","2026-02-22_16.webp","2026-04-10_8.webp","2026-04-10_9.webp"),
  "evidence": ["Contact sheets 071: dã ngoại 22/02/2026 + sinh nhật 5 tuổi 10/04/2026"],
  "context": "Dã ngoại 22/02/2026 và tiệc sinh nhật 5 tuổi của Yên 10/04/2026."}
]


def main() -> None:
    raw = OBS.read_text(encoding="utf-8")
    data = json.loads(re.sub(r"^window\.BABY_STORY_OBSERVATIONS = |;\s*$", "", raw.strip()))
    existing_ids = {e.get("sceneId") for e in data.get("events", [])}
    claimed = set()
    for ev in data.get("events", []) + data.get("milestones", []):
        claimed.update(ev.get("media", []))
    added = skipped_existing = skipped_claimed_all = 0
    for ch in CHAPTERS:
        if ch["sceneId"] in existing_ids:
            skipped_existing += 1
            continue
        kept = [s for s in ch["media"] if s not in claimed]
        dropped = [s for s in ch["media"] if s in claimed]
        if not kept:
            skipped_claimed_all += 1
            print(f"[skip] {ch['sceneId']}: toàn bộ media đã claim")
            continue
        if dropped:
            print(f"[note] {ch['sceneId']}: bỏ {len(dropped)} media đã claim")
        ch["media"] = kept
        data["events"].append(ch)
        existing_ids.add(ch["sceneId"])
        added += 1
    for ev in data["events"]:
        if ev.get("sensitive"):
            data.setdefault("excludePreview", [])
            have = set(data["excludePreview"])
            data["excludePreview"].extend([s for s in ev["media"] if s not in have])
    # chương phi sensitive: thêm ảnh vào previewCandidates
    have_preview = set(data.get("previewCandidates", []))
    for ev in data["events"]:
        if ev.get("sensitive"):
            continue
        for src in ev["media"]:
            if src.endswith(".webp") and src not in have_preview:
                data["previewCandidates"].append(src)
                have_preview.add(src)
    OBS.write_text("window.BABY_STORY_OBSERVATIONS = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n",
                   encoding="utf-8")
    total_media = sum(len(e["media"]) for e in data["events"])
    print(f"thêm {added} chương (bỏ qua {skipped_existing} đã có, {skipped_claimed_all} trùng claim); "
          f"tổng events: {len(data['events'])}, media events: {total_media}, previewCandidates: {len(data['previewCandidates'])}")


if __name__ == "__main__":
    main()
